### ISSUE TITLE
Missing retina_assigner?

### ISSUE THREAD

**Issue by yarkable** [zehuichen123/DDOD#2]
Hi, thanks for your great work. But when I run this code, it threw an error with `AttributeError: 'ConfigDict' object has no attribute 'retina_assigner'`. I guess `self.train_cfg.retina_assigner` in `atss_r50_1x.py` is missing. Can you please provide it?

**Comment by zehuichen123** [comment]
Hi @yarkable, Thanks for your interest in our work! I reused `atss_iou_head.py` for other experiments but forgot to roll it back. Currently, I've corrected the code in `atss_iou_head.py` and checked there is no error with `atss_r50_1x.py` config.

**Comment by yarkable** [comment]
I've got it, thanks for your quick reply!
