### ISSUE TITLE
About WiderFace.

### ISSUE THREAD

**Issue by StetchPlane** [zehuichen123/DDOD#7]
When ddod is applied to wideface, does the testing process adopt the method in tinaface?
In addition, could you release the code to apply ddod to widerface?

**Comment by zehuichen123** [comment]
1) Almost the same. The only difference is that we do not use shifts for multi-scale testing. 
2) Currently, we have no plan for that, the related code was lost at my last intern company :(

**Comment by StetchPlane** [comment]
Thanks for your answer.
