### ISSUE TITLE
About Widerface

### ISSUE THREAD

**Issue by StetchPlane** [zehuichen123/DDOD#8]
How is anchor set when ddod is applied to widerface?(including base_sizes, ratios, scales_per_octave, octave_base_scale)

**Comment by zehuichen123** [comment]
We simply adopt the same settings in TinaFace, as well as the test-time augmentation. Note that you may need to add clip_gradient to stabilize the training process.

**Comment by zehuichen123** [comment]
And you may need to borrow some code from https://github.com/Media-Smart/vedadet where mmdet does not implement, like data augmentation.

**Comment by StetchPlane** [comment]
I added three innovative points in ddod to tinaface before, and the other settings did not change, but the experimental accuracy decreased, especially the "atss_cost_assigner". However, I did not use clip_gradient in this process.

**Comment by zehuichen123** [comment]
Yes, if clip_gradient is not added, the result is quite bad, perhaps 89/90? I did not remember exactly. We infer that the reason mainly stems from the vast small gt boxes in WiderFace.

**Comment by StetchPlane** [comment]
![Snipaste_2021-11-18_16-40-03](https://user-images.githubusercontent.com/46260162/142380935-8594541c-d908-454e-9040-279de7ef1f0d.png)
What is the experimental setting of "clip_gradient"? Do you still have an impression?

**Comment by zehuichen123** [comment]
Yes. If not, maybe 10 for max_norm. The loss will be quite different from the one without clip_gradient at the very beginning of the training.

**Comment by StetchPlane** [comment]
Thank you very much for your patience.
